### ISSUE TITLE
Argument Null Reference - newest build

### ISSUE THREAD

**Issue by Lynical** [Sen66/PokemonGo-Bot#35]
Title says it pretty much @Sen66 
I'm getting it after like 10 minutes of running.

**Comment by Sen66** [comment]
PTC or Google?

**Comment by Lynical** [comment]
Google, I never use PTC.

I also made a feature suggestion

**Comment by Sen66** [comment]
Please write here for that issue.
I need more details.
Are you inputing your Refresh token manually?
When is the error coming? ALWAYS after 10 minutes or random?

**Comment by Phrex** [comment]
Yes, i have this bug too. Im using it with Google account, as i saw its randomly i can attach pic too if you want.

**Comment by Phrex** [comment]
I caught the problem.

http://m.imgur.com/YD79mHh

**Comment by Phrex** [comment]
Okay, so when any problem which triggers an exception appears, the program wants to reconnect to your Google Account, but there is no GoogleRefreshToken was set, and it causes a NULL exception, because in the app.config the Token's value is NULL, so put your Google key in app.config, it will solve that problem. Anyways, its working fine.

**Comment by Sen66** [comment]
Start the program without Visual Studio fixes it also,

**Comment by Sen66** [comment]
should be fixed.
